CREATE TABLE `campaign_model_runs` (
	`invocation_id` text PRIMARY KEY NOT NULL,
	`campaign_id` text NOT NULL,
	`outcome_id` text NOT NULL,
	`role` text NOT NULL,
	`assessment_id` text,
	`evidence_hash` text,
	`status` text NOT NULL,
	`failure_class` text,
	`started_at_epoch_ms` integer NOT NULL,
	`completed_at_epoch_ms` integer,
	`elapsed_ms` integer,
	`repository_id` text,
	`repository` text,
	`profile` text,
	`configured_provider` text,
	`configured_model` text,
	`actual_provider` text,
	`actual_model` text,
	`adapter` text,
	`service_tier` text,
	`reasoning_effort` text,
	`usage` text
);
